#!/bin/bash

echo "=== Setting up permanent domain for Terminal Web ==="
echo ""

TUNNEL_ID="418b4665-6f69-4453-aec6-9216e97775e5"
TUNNEL_NAME="terminal-web-1752420453"

echo "1. First, log in to Cloudflare Dashboard:"
echo "   https://dash.cloudflare.com"
echo ""
echo "2. Go to Zero Trust > Access > Tunnels"
echo ""
echo "3. Find your tunnel: $TUNNEL_NAME"
echo ""
echo "4. Click on it and go to 'Public Hostname' tab"
echo ""
echo "5. Add a public hostname:"
echo "   - Subdomain: terminal (or whatever you prefer)"
echo "   - Domain: Select your domain"
echo "   - Path: leave empty"
echo "   - Service: http://localhost:3000"
echo ""
echo "6. Save the configuration"
echo ""
echo "After that, run the tunnel with:"
echo "cloudflared tunnel run $TUNNEL_NAME"
echo ""
echo "Your terminal will be available at:"
echo "https://terminal.your-domain.com"